export const Backgrounds = {
  "Antique White": "AntiqueWhite",
  "Phantom Green": "PhantomGreen",
  "Cannoli Cream": "CannoliCream",
  "Solitary Star": "SolitaryStar",
  "Bit Of Blue": "BitOfBlue",
  Buttercream: "Buttercream",
  Marshmallow: "Marshmallow",
  "Snow White": "SnowWhite",
  "Powder Puff": "PowderPuff",
  "Vanilla Ice": "VanillaIce",
};

export const backgroundUrls = {
  AntiqueWhite: "/Y00TWallpapersImages/AntiqueWhite.png",
  PhantomGreen: "/Y00TWallpapersImages/PhantomGreen.png",
  CannoliCream: "/Y00TWallpapersImages/CannoliCream.png",
  SolitaryStar: "/Y00TWallpapersImages/SolitaryStar.png",
  BitOfBlue: "/Y00TWallpapersImages/BitOfBlue.png",
  Buttercream: "/Y00TWallpapersImages/Buttercream.png",
  Marshmallow: "/Y00TWallpapersImages/Marshmallow.png",
  SnowWhite: "/Y00TWallpapersImages/SnowWhite.png",
  PowderPuff: "/Y00TWallpapersImages/PowderPuff.png",
  VanillaIce: "/Y00TWallpapersImages/VanillaIce.png",
};

export const Furs = {
  Hazel: "Hazel",
  Wheat: "Wheat",
  Stone: "Stone",
  Bone: "Bone",
  Eggnog: "Eggnog",
  Pewter: "Pewter",
  Tumbleweed: "Tumbleweed",
  Chestnut: "Chestnut",
  "Sand Dollar": "SandDollar",
  "Pink Marshmallow": "PinkMarshmallow",
  "Paradise Green": "ParadiseGreen",
  "1/1": "oneofone",
};

export const FurColors = {
  Hazel: "#c28256",
  Wheat: "#a89383",
  Stone: "#7d8385",
  Bone: "#99978d",
  Eggnog: "#94816a",
  Pewter: "#82858c",
  Tumbleweed: "#a7866c",
  Chestnut: "#946342",
  "Sand Dollar": "#9e9286",
  "Pink Marshmallow": "#ce8992",
  "Paradise Green": "#62b191",
  "1/1": "#FFA500",
};

export const Heads = {
  Helmet: "Helmet",
  "Color Block Halo": "ColorBlockHalo",
  "Backwards Snapback": "BackwardsSnapback",
  "Fast Food Visor": "FastFoodVisor",
  "Red Horns": "RedHorns",
  Mullet: "Mullet",
  "24k Gold Shoey Guzzler": "GoldShoeyGuzzler",
  "Frank Headband": "FrankHeadband",
  "Pyrite Crown": "PyriteCrown",
  "Fuzzy Banana Bucket Hat": "FuzzyBananaBucketHat",
  "Cool Beanie": "CoolBeanie",
  "Orange Beanie": "OrangeBeanie",
  "Champ Hat": "ChampHat",
  "Rockstar Hair": "RockstarHair",
  "Windswept Hair": "WindsweptHair",
  Undercut: "Undercut",
  "Skinny Headband": "SkinnyHeadband",
  "Banana Beanie": "BananaBeanie",
  Headphones: "Headphones",
  "Chill Hat": "ChillHat",
  "Truck Trucker": "TruckTrucker",
  "Minimalist Camo Cap": "MinimalistCamoCap",
  None: "None",
  "Free Snapback": "FreeSnapback",
  "Down Bad Snapback": "DownBadSnapback",
  "Happy Hat": "HappyHat",
  "Bucket Hat": "BucketHat",
  "Beanie (blackout)": "BlackoutBeanie",
  "W Visor": "WVisor",
  "Skull Trucker Hat": "SkullTruckerHat",
  "Money Bands": "MoneyBands",
  "Spiky Hair": "SpikyHair",
  "Flame Hat": "FlameHat",
  "Big Cowboy Hat": "BigCowboyHat",
};

export const HeadColors = {
  Helmet: "#FFA500",
  "Color Block Halo": "#FFA500",
  "Backwards Snapback": "#FFA500",
  "Fast Food Visor": "#FFA500",
  "Red Horns": "#FFA500",
  Mullet: "#FFA500",
  "24k Gold Shoey Guzzler": "#FFA500",
  "Frank Headband": "#FFA500",
  "Pyrite Crown": "#FFA500",
  "Fuzzy Banana Bucket Hat": "#FFA500",
  "Cool Beanie": "#FFA500",
  "Orange Beanie": "#FFA500",
  "Champ Hat": "#FFA500",
  "Rockstar Hair": "#FFA500",
  "Windswept Hair": "#FFA500",
  Undercut: "#FFA500",
  "Skinny Headband": "#FFA500",
  "Banana Beanie": "#FFA500",
  Headphones: "#FFA500",
  "Chill Hat": "#FFA500",
  "Truck Trucker": "#FFA500",
  "Minimalist Camo Cap": "#FFA500",
  None: "#FFA500",
  "Free Snapback": "#FFA500",
  "Down Bad Snapback": "#FFA500",
  "Happy Hat": "#FFA500",
  "Bucket Hat": "#FFA500",
  "Beanie (blackout)": "#FFA500",
  "W Visor": "#FFA500",
  "Skull Trucker Hat": "#FFA500",
  "Money Bands": "#FFA500",
  "Spiky Hair": "#FFA500",
  "Flame Hat": "#FFA500",
  "Big Cowboy Hat": "#FFA500",
};

export const Clothes = {
  "Fast Food Polo": "Fast Food Polo",
  "Happy Hoodie": "Happy Hoodie",
  "The Hoodie": "The Hoodie",
  "Basketball Jersey": "Basketball Jersey",
  "Cherry Puffer": "Cherry Puffer",
  None: "None",
  "Ace Cardigan": "Ace Cardigan",
  "Angler Vest": "Angler Vest",
  "C.R.E.A.M. Hoodie": "C.R.E.A.M. Hoodie",
  "Orange Hoodie": "Orange Hoodie",
  "Sunday Shirt": "Sunday Shirt",
  "Bear Coat": "Bear Coat",
  "Army T-shirt": "Army T-shirt",
  "Black Puff Jacket": "Black Puff Jacket",
  "Banana Hazmat": "Banana Hazmat",
  "Billionaire Zip-up": "Billionaire Zip-up",
  "Jacksonhole Jacket": "Jacksonhole Jacket",
  "Cashmere Turtleneck": "Cashmere Turtleneck",
  "Black Tracksuit": "Black Tracksuit",
  "Fast Jacket": "Fast Jacket",
  Mechanic: "Mechanic",
  "Rugby Shirt": "Rugby Shirt",
  "Windbreaker (blackout)": "Windbreaker (blackout)",
  "Cream Flannel": "Cream Flannel",
  "Marshmallow Puffer": "Marshmallow Puffer",
  "Stolen Hotel Robe": "Stolen Hotel Robe",
  "Banana Puffer": "Banana Puffer",
  "Miracle Jersey": "Miracle Jersey",
  "Rare T-shirt": "Rare T-shirt",
  "Varsity Jacket": "Varsity Jacket",
  "Nice Overalls": "Nice Overalls",
  "Summer Shirt": "Summer Shirt",
  "Blue Sky Hoodie": "Blue Sky Hoodie",
  "Classic Suit": "Classic Suit",
  "Thrifted Denim Jacket": "Thrifted Denim Jacket",
  "Football Jersey": "Football Jersey",
  "Blue Headphones": "Blue Headphones",
  "Blob Suit": "Blob Suit",
  Professor: "Professor",
  "Baseball Hoodie": "Baseball Hoodie",
  "1/1": "1/1",
};

export const ClothesColors = {
  "Fast Food Polo": "#FFA500",
  "Happy Hoodie": "#FFA500",
  "The Hoodie": "#FFA500",
  "Basketball Jersey": "#FFA500",
  "Cherry Puffer": "#FFA500",
  None: "#FFA500",
  "Ace Cardigan": "#FFA500",
  "Angler Vest": "#FFA500",
  "C.R.E.A.M. Hoodie": "#FFA500",
  "Orange Hoodie": "#FFA500",
  "Sunday Shirt": "#00FF00",
  "Bear Coat": "#FFA500",
  "Army T-shirt": "#FFA500",
  "Black Puff Jacket": "#FFA500",
  "Banana Hazmat": "#FFA500",
  "Billionaire Zip-up": "#FFA500",
  "Jacksonhole Jacket": "#FFA500",
  "Cashmere Turtleneck": "#FFA500",
  "Black Tracksuit": "#FFA500",
  "Fast Jacket": "#FFA500",
  Mechanic: "#FFA500",
  "Rugby Shirt": "#FFA500",
  "Windbreaker (blackout)": "#FFA500",
  "Cream Flannel": "#FFA500",
  "Marshmallow Puffer": "#FFA500",
  "Stolen Hotel Robe": "#FFA500",
  "Banana Puffer": "#FFA500",
  "Miracle Jersey": "#FFA500",
  "Rare T-shirt": "#FFA500",
  "Varsity Jacket": "#FFA500",
  "Nice Overalls": "#FFA500",
  "Summer Shirt": "#FFA500",
  "Blue Sky Hoodie": "#FFA500",
  "Classic Suit": "#FFA500",
  "Thrifted Denim Jacket": "#FFA500",
  "Football Jersey": "#FFA500",
  "Blue Headphones": "#FFA500",
  "Blob Suit": "#FFA500",
  Professor: "#FFA500",
  "Baseball Hoodie": "#FFA500",
  "1/1": "#FFA500",
};

export const Eyewears = {
  "Blue Light Glasses": "BlueLightGlasses",
  Nouns: "Nouns",
  "Win-Win Shades": "WinWinShades",
  Trapezoids: "Trapezoids",
  "Banksy Goggles": "BanksyGoggles",
  "Tints (yellow)": "TintsYellow",
  "6d Glasses": "SixdGlasses",
  "Lensless Glasses": "LenslessGlasses",
  "Tints (blue)": "TintsBlue",
  "Windsors (blackout)": "WindsorsBlackout",
  "Abbey Roads": "AbbeyRoads",
  "Rembrandt Goggles": "RembrandtGoggles",
  "Retro Apple": "RetroApple",
  "Tints (red)": "TintsRed",
  "Mona Lisas": "MonaLisas",
  "Rounded Squares (blackout)": "RoundedSquaresBlackout",
  "24k Gold Blocks": "GoldBlocks24k",
  "Aviators (blackout)": "AviatorsBlackout",
  "Matisse Frames": "MatisseFrames",
  Warhols: "Warhols",
  Sunflowers: "Sunflowers",
  "Cali Sunset": "CaliSunset",
  "Hockney Squares": "HockneySquares",
  "Van Goghs": "VanGoghs",
  Heatwaves: "Heatwaves",
  "Last Supper Squares": "LastSupperSquares",
  "Orange Soda Shades": "OrangeSodaShades",
  "Dieter Rams": "DieterRams",
  "Golden Hour Frames": "GoldenHourFrames",
  Pollocks: "Pollocks",
  "Melrose Bricks": "MelroseBricks",
  None: "None",
  "Wayfarers (blackout)": "WayfarersBlackout",
  "Green Bricks": "GreenBricks",
  "Mondrian Squares": "MondrianSquares",
  "Grand Budapest Shades": "GrandBudapestShades",
  "Radiohead Squares": "RadioheadSquares",
  "Cobain Goggles": "CobainGoggles",
  "Monet Squares": "MonetSquares",
  "Ive Unibody": "IveUnibody",
  "1/1": "OneToOne",
};

export const EyewearColors = {
  "Blue Light Glasses": "#FFA500",
  Nouns: "#FFA500",
  "Win-Win Shades": "#FFA500",
  Trapezoids: "#FFA500",
  "Banksy Goggles": "#FFA500",
  "Tints (yellow)": "#FFA500",
  "6d Glasses": "#FFA500",
  "Lensless Glasses": "#FFA500",
  "Tints (blue)": "#FFA500",
  "Windsors (blackout)": "#FFA500",
  "Abbey Roads": "#FFA500",
  "Rembrandt Goggles": "#FFA500",
  "Retro Apple": "#0000ff",
  "Tints (red)": "#FFA500",
  "Mona Lisas": "#FFA500",
  "Rounded Squares (blackout)": "#FFA500",
  "24k Gold Blocks": "#FFA500",
  "Aviators (blackout)": "#FFA500",
  "Matisse Frames": "#FFA500",
  Warhols: "#FFA500",
  Sunflowers: "#FFA500",
  "Cali Sunset": "#FFA500",
  "Hockney Squares": "#FFA500",
  "Van Goghs": "#FFA500",
  Heatwaves: "#FFA500",
  "Last Supper Squares": "#FFA500",
  "Orange Soda Shades": "#FFA500",
  "Dieter Rams": "#FFA500",
  "Golden Hour Frames": "#FFA500",
  Pollocks: "#FFA500",
  "Melrose Bricks": "#FFA500",
  None: "#FFA500",
  "Wayfarers (blackout)": "#FFA500",
  "Green Bricks": "#FFA500",
  "Mondrian Squares": "#FFA500",
  "Grand Budapest Shades": "#FFA500",
  "Radiohead Squares": "#FFA500",
  "Cobain Goggles": "#FFA500",
  "Monet Squares": "#FFA500",
  "Ive Unibody": "#FFA500",
  "1/1": "#FFA500",
};
